language: cpp

compiler:
 - gcc
 - clang

before_install:
 - sudo add-apt-repository ppa:zarquon42/precise-backports -y
 - sudo apt-get update -qq
 - sudo apt-get install -y cmake ibboost1.55-dev libboost1.55 libinsighttoolkit4-dev

script:
 - cd Tools
 - make

