language: cpp

compiler:
 - gcc
 - clang

before_install:
 - sudo sudo add-apt-repository universe -y
 - sudo apt-get update -qq
 - sudo apt-get install -y cmake libboost-dev libinsighttoolkit4-dev

script:
 - cd Tools
 - make

