
language: cpp

sudo: required

dist: trusty

addons:
  apt:
    packages:
    - cmake
    - libboost-dev
    - python3
    - python3-pip
    - python3-yaml
    - lcov

matrix:
  include:
    - os: osx
      compiler: clang
      env: ITK_VERSION=v4.8.0 TRAVIS_PYTHON_VERSION=3.5
    - os: osx
      compiler: clang
      env: ITK_VERSION=v4.10.0 TRAVIS_PYTHON_VERSION=3.5
    - os: linux
      compiler: gcc
      env: ITK_VERSION=v4.8.0 TRAVIS_PYTHON_VERSION=3.5
    - os: linux
      compiler: gcc
      env: ITK_VERSION=v4.10.0 TRAVIS_PYTHON_VERSION=3.5

cache:
  - directories:
    - $HOME/itk-v4.8.0
    - $HOME/itk-v4.8.0-build
    - $HOME/itk-v4.10.0
    - $HOME/itk-v4.10.0-build

before_install:
  - if test $TRAVIS_OS_NAME == osx ; then brew update; brew install python3 lcov; brew upgrade libpng; fi

before_script:
  - export NUM_THREADS=4
  - export ITK_SOURCE_DIR=$HOME/itk-${ITK_VERSION}
  - export ITK_BUILD_DIR=${ITK_SOURCE_DIR}-build
  - if ! test -e ${ITK_SOURCE_DIR}/CMakeLists.txt; then rm -fr $ITK_SOURCE_DIR; fi
  - if ! test -d ${ITK_SOURCE_DIR}; then git clone --branch ${ITK_VERSION} git://itk.org/ITK.git ${ITK_SOURCE_DIR}; fi
  - if ! test -d ${ITK_BUILD_DIR}; then mkdir ${ITK_BUILD_DIR}; fi
  - cd ${ITK_BUILD_DIR}
  - cmake ${ITK_SOURCE_DIR}
    -DCMAKE_BUILD_TYPE=Release
    -DBUILD_EXAMPLES=OFF
    -DBUILD_TESTING=OFF
    -DModule_ITKReview=ON
  - make --jobs=$NUM_THREADS --keep-going
  - cd -
  - sh install_modules.sh
  - python3 -m pip install codecov
  - python3 setup.py install
  - cd externals/TCIAExplorer
  - python3 setup.py install
  - cd -

script:
  - mkdir build
  - cd build
  - cmake .. -DENABLE_COVERAGE=On && make && make test
  - make gcov
  - make lcov
  - cd -
  - python3 download_lungx_tcia.py
  - coverage run run.py
  - codecov

after_success:
  - bash <(curl -s https://codecov.io/bash) -X gcov
