language: cpp

compiler:
 - gcc
 - clang

before_install:
 - sudo add-apt-repository ppa:zarquon42/precise-backports -y
 - sudo apt-get install -y cmake libinsighttoolkit4-dev

script:
 - cd Tools
 - make

