
language: cpp

sudo: required

dist: trusty

addons:
  apt:
    packages:
    - cmake
    - libboost-dev

matrix:
  include:
    - os: osx
      compiler: clang
      env: ITK_VERSION=v4.8.0
    - os: osx
      compiler: clang
      env: ITK_VERSION=v4.9.0
    - os: osx
      compiler: clang
      env: ITK_VERSION=v4.10.0
    - os: linux
      compiler: gcc
      env: ITK_VERSION=v4.8.0
    - os: linux
      compiler: gcc
      env: ITK_VERSION=v4.9.0
    - os: linux
      compiler: gcc
      env: ITK_VERSION=v4.10.0

cache:
  - directories:
    - $HOME/itk-v4.8.0
    - $HOME/itk-v4.8.0-build
    - $HOME/itk-v4.9.0
    - $HOME/itk-v4.9.0-build
    - $HOME/itk-v4.10.0
    - $HOME/itk-v4.10.0-build

before_install:
  - pip install conda
  - sh install_modules.sh  

before_script:
  - export NUM_THREADS=4
  - export ITK_SOURCE_DIR=$HOME/itk-${ITK_VERSION}
  - export ITK_BUILD_DIR=${ITK_SOURCE_DIR}-build
  - if ! test -e ${ITK_SOURCE_DIR}/CMakeLists.txt; then rm -fr $ITK_SOURCE_DIR; fi
  - if ! test -d ${ITK_SOURCE_DIR}; then git clone --branch ${ITK_VERSION} git://itk.org/ITK.git ${ITK_SOURCE_DIR}; fi
  - if ! test -d ${ITK_BUILD_DIR}; then mkdir ${ITK_BUILD_DIR}; fi
  - cd ${ITK_BUILD_DIR}
  - cmake ${ITK_SOURCE_DIR}
    -DCMAKE_BUILD_TYPE=Release
    -DBUILD_EXAMPLES=OFF
    -DBUILD_TESTING=OFF
    -DModule_ITKReview=ON
  - make --jobs=$NUM_THREADS --keep-going
  - cd -

script:
  - cd Tools
  - make --jobs=$NUM_THREADS --keep-going all
  - python run.py
  
  